name: Deploy Laravel Application

on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t diockerhub/laravel-app .

      - name: Push Docker image to Docker Hub
        run: docker push diockerhub/laravel-app:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull diockerhub/laravel-app:latest

      - name: Create network if not exists
        run: |
          if ! docker network inspect backend-network >/dev/null 2>&1; then
            docker network create backend-network
          fi

      - name: Delete old container
        run: sudo docker rm -f laravel-app-container || true

      - name: Run Docker container
        run: sudo docker run -d --network backend-network -p 9000:9000 --name laravel-app-container  --env-file .env diockerhub/laravel-app:latest
 
      - name: Run Sequelize migrations
        run: sudo docker exec node-app-container npx sequelize-cli db:migrate