name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Ensure .env is not a directory
        run: |
          if [ -d ".env" ]; then
            rm -rf .env
          fi

      - name: Create .env file
        run: |
          touch .env
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

         
      - name: List directory contents after .env creation
        run: ls -la

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Verify .env file
        run: |
          if [ -d ".env" ]; then
            echo ".env is a directory"
            exit 1
          elif [ -f ".env" ]; then
            echo ".env is a file"
            cat .env
          else
            echo ".env does not exist"
            exit 1
          fi

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t diockerhub/laravel-app .

      - name: Push Docker image to Docker Hub
        run: docker push diockerhub/laravel-app:latest

      # - name: Login to GitHub Packages
      #   run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
      # - name: Build Docker image
      #   run: docker build -t ghcr.io/${{ github.repository_owner }}/gastos-laravel/laravel-app:latest .
    
      # - name: Push Docker image to GitHub Packages
      #   run: docker push ghcr.io/${{ github.repository_owner }}/gastos-laravel/laravel-app:latest
    

      - name: Upload .env file
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Ensure .env is not a directory before download
        run: |
          if [ -d ".env" ]; then
            rm -rf .env
          fi

      - name: Download .env file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .

      - name: List directory contents after download
        run: ls -la

      - name: Find .env file location
        run: find . -name ".env"

      - name: Move .env file if necessary
        run: |
          if [ -f "env-file/.env" ]; then
            mv env-file/.env .
          fi

      - name: Ensure .env is not a directory after download
        run: |
          if [ -d ".env" ]; then
            echo ".env is a directory"
            exit 1
          elif [ -f ".env" ]; then
            echo ".env is a file"
            cat .env
          else
            echo ".env does not exist"
            exit 1
          fi

      - name: Pull image from Docker Hub
        run: sudo docker pull diockerhub/laravel-app:latest

      # - name: Pull image from GitHub Packages
      #   run: sudo docker pull ghcr.io/${{ github.repository_owner }}/gastos-laravel/laravel-app:latest



      - name: Create network if not exists
        run: |
          if ! sudo docker network inspect backend-network >/dev/null 2>&1; then
            sudo docker network create backend-network
          fi

      - name: Delete old container
        run: sudo docker rm -f laravel-app-container || true

      - name: Run Docker container
        run: sudo docker run -d --network backend-network -p 8000:8000 --name laravel-app-container --env-file .env diockerhub/laravel-app:latest

      - name: Run Laravel migrations
        run: sudo docker exec laravel-app-container php artisan migrate --force

      